#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINKQ_pallavi.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pallavistocksystem")]
	public partial class DataLINKQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    #endregion
		
		public DataLINKQDataContext() : 
				base(global::LINKQ_pallavi.Properties.Settings.Default.pallavistocksystemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataLINKQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLINKQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLINKQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLINKQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Com_ID;
		
		private string _Com_code;
		
		private string _Com_Name;
		
		private string _Com_Add;
		
		private string _Com_Contact;
		
		private int _Created_ID;
		
		private System.DateTime _Create_Date;
		
		private int _Updated_ID;
		
		private System.DateTime _Updated_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCom_IDChanging(int value);
    partial void OnCom_IDChanged();
    partial void OnCom_codeChanging(string value);
    partial void OnCom_codeChanged();
    partial void OnCom_NameChanging(string value);
    partial void OnCom_NameChanged();
    partial void OnCom_AddChanging(string value);
    partial void OnCom_AddChanged();
    partial void OnCom_ContactChanging(string value);
    partial void OnCom_ContactChanged();
    partial void OnCreated_IDChanging(int value);
    partial void OnCreated_IDChanged();
    partial void OnCreate_DateChanging(System.DateTime value);
    partial void OnCreate_DateChanged();
    partial void OnUpdated_IDChanging(int value);
    partial void OnUpdated_IDChanged();
    partial void OnUpdated_DateChanging(System.DateTime value);
    partial void OnUpdated_DateChanged();
    #endregion
		
		public Company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Com_ID
		{
			get
			{
				return this._Com_ID;
			}
			set
			{
				if ((this._Com_ID != value))
				{
					this.OnCom_IDChanging(value);
					this.SendPropertyChanging();
					this._Com_ID = value;
					this.SendPropertyChanged("Com_ID");
					this.OnCom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Com_code
		{
			get
			{
				return this._Com_code;
			}
			set
			{
				if ((this._Com_code != value))
				{
					this.OnCom_codeChanging(value);
					this.SendPropertyChanging();
					this._Com_code = value;
					this.SendPropertyChanged("Com_code");
					this.OnCom_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Com_Name
		{
			get
			{
				return this._Com_Name;
			}
			set
			{
				if ((this._Com_Name != value))
				{
					this.OnCom_NameChanging(value);
					this.SendPropertyChanging();
					this._Com_Name = value;
					this.SendPropertyChanged("Com_Name");
					this.OnCom_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Add", DbType="VarChar(200)")]
		public string Com_Add
		{
			get
			{
				return this._Com_Add;
			}
			set
			{
				if ((this._Com_Add != value))
				{
					this.OnCom_AddChanging(value);
					this.SendPropertyChanging();
					this._Com_Add = value;
					this.SendPropertyChanged("Com_Add");
					this.OnCom_AddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Com_Contact", DbType="VarChar(200)")]
		public string Com_Contact
		{
			get
			{
				return this._Com_Contact;
			}
			set
			{
				if ((this._Com_Contact != value))
				{
					this.OnCom_ContactChanging(value);
					this.SendPropertyChanging();
					this._Com_Contact = value;
					this.SendPropertyChanged("Com_Contact");
					this.OnCom_ContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created_ID", DbType="Int NOT NULL")]
		public int Created_ID
		{
			get
			{
				return this._Created_ID;
			}
			set
			{
				if ((this._Created_ID != value))
				{
					this.OnCreated_IDChanging(value);
					this.SendPropertyChanging();
					this._Created_ID = value;
					this.SendPropertyChanged("Created_ID");
					this.OnCreated_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Create_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Create_Date
		{
			get
			{
				return this._Create_Date;
			}
			set
			{
				if ((this._Create_Date != value))
				{
					this.OnCreate_DateChanging(value);
					this.SendPropertyChanging();
					this._Create_Date = value;
					this.SendPropertyChanged("Create_Date");
					this.OnCreate_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated_ID", DbType="Int NOT NULL")]
		public int Updated_ID
		{
			get
			{
				return this._Updated_ID;
			}
			set
			{
				if ((this._Updated_ID != value))
				{
					this.OnUpdated_IDChanging(value);
					this.SendPropertyChanging();
					this._Updated_ID = value;
					this.SendPropertyChanged("Updated_ID");
					this.OnUpdated_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Updated_Date
		{
			get
			{
				return this._Updated_Date;
			}
			set
			{
				if ((this._Updated_Date != value))
				{
					this.OnUpdated_DateChanging(value);
					this.SendPropertyChanging();
					this._Updated_Date = value;
					this.SendPropertyChanged("Updated_Date");
					this.OnUpdated_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
